---
- name: Test Jenkins
  ansible.builtin.command: "/usr/local/bin/kubectl create namespace valen"
  register: namespace
  changed_when: false


# - name: Test get pod
#   ansible.builtin.command: sudo kubectl get po -A
#   changed_when: ture
