---
- name: Test Jenkins
  ansible.builtin.command: kubectl create namespace few
  changed_when: false


# - name: Test get pod
#   ansible.builtin.command: sudo kubectl get po -A
#   changed_when: ture
